/*
 * Code was copied from java example so there is a .NET version 
 * to work with.
 * 
 * Copyright 2014 Yubico.
 * Copyright 2014 Google Inc. All rights reserved.
 *
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file or at
 * https://developers.google.com/open-source/licenses/bsd
 */
 
using System.Collections.Generic;
using u2flib.Crypto;
using u2flib.Data;
using u2flib.Data.Messages;
using u2flib.Util;

namespace u2flib
{
    public class U2F
    {
        public const string U2FVersion = "U2F_V2";
        public static readonly IChallengeGenerator ChallengeGenerator = new RandomChallengeGenerator();
        public static readonly ICrypto Crypto = new BouncyCastleCrypto();
        private const string AuthenticateTyp = "navigator.id.getAssertion";
        private const string RegisterType = "navigator.id.finishEnrollment";
        
        /// <summary>
        /// Initiates the registration of a device. 
        /// </summary>
        /// <param name="appId">appId the U2F AppID. Set this to the Web Origin of the login page, unless you need to </param>
        /// <returns>a StartedRegistration, which should be sent to the client and temporary saved by the server. support logging in from multiple Web Origins.</returns>
        public static StartedRegistration StartRegistration(string appId)
        {
            byte[] challenge = ChallengeGenerator.GenerateChallenge();
            string challengeBase64 = Utils.ByteArrayToBase64String(challenge);

            return new StartedRegistration(challengeBase64, appId);
        }

        /// <summary>
        /// Finishes a previously started registration.
        /// </summary>
        /// <param name="startedRegistration">Registration data created by calling startRegistration</param>
        /// <param name="tokenResponse">tokenResponse the response from the token/client.</param>
        /// <param name="facets">A list of valid facets to verify against.</param>
        /// <returns>a DeviceRegistration object, holding information about the registered device. Servers should persist this.</returns>
        public static DeviceRegistration FinishRegistration(StartedRegistration startedRegistration,
                                                            RegisterResponse tokenResponse, HashSet<string> facets = null)
        {
            ClientData clientData = tokenResponse.GetClientData();
            clientData.CheckContent(RegisterType, startedRegistration.Challenge, facets);

            RawRegisterResponse rawRegisterResponse = RawRegisterResponse.FromBase64(tokenResponse.RegistrationData);
            rawRegisterResponse.CheckSignature(startedRegistration.AppId, clientData.AsJson());

            return rawRegisterResponse.CreateDevice();
        }
        
        /// <summary>
        /// Initiates the authentication process.
        /// </summary>
        /// <param name="appId">appId the U2F AppID. Set this to the Web Origin of the login page, unless you need to support logging in from multiple Web Origins.</param>
        /// <param name="deviceRegistration">deviceRegistration the DeviceRegistration for which to initiate authentication.</param>
        /// <returns>a StartedAuthentication which should be sent to the client and temporary saved by the server.</returns>
        public static StartedAuthentication StartAuthentication(string appId, DeviceRegistration deviceRegistration)
        {
            return StartAuthentication(appId, deviceRegistration, ChallengeGenerator.GenerateChallenge());
        }

        /// <summary>
        /// Initiates the authentication process.
        /// </summary>
        /// <param name="appId">appId the U2F AppID. Set this to the Web Origin of the login page, unless you need to support logging in from multiple Web Origins.</param>
        /// <param name="deviceRegistration">deviceRegistration the DeviceRegistration for which to initiate authentication.</param>
        /// <param name="challenge">challenge random generated byte[] from IChallengeGenerator.</param>
        /// <returns>a StartedAuthentication which should be sent to the client and temporary saved by the server.</returns>
        public static StartedAuthentication StartAuthentication(string appId, DeviceRegistration deviceRegistration, byte[] challenge)
        {
            return new StartedAuthentication(
                Utils.ByteArrayToBase64String(challenge),
                appId,
                Utils.ByteArrayToBase64String(deviceRegistration.KeyHandle));
        }

        /// <summary>
        /// Finishes a previously started authentication.
        /// </summary>
        /// <remarks>This method will throw an exception if the device fails authentication.</remarks>
        /// <param name="startedAuthentication">the authentication data created by calling startAuthentication</param>
        /// <param name="response">response the response from the token/client.</param>
        /// <param name="deviceRegistration">the devices currently registered to the user.</param>
        /// <param name="facets">A list of valid facets to verify against.</param>
        public static void FinishAuthentication(StartedAuthentication startedAuthentication,
                                                              AuthenticateResponse response,
                                                              DeviceRegistration deviceRegistration,
                                                              HashSet<string> facets = null)
        {
            ClientData clientData = response.GetClientData();
            clientData.CheckContent(AuthenticateTyp, startedAuthentication.Challenge, facets);

            RawAuthenticateResponse authenticateResponse = RawAuthenticateResponse.FromBase64(response.SignatureData);
            authenticateResponse.CheckSignature(startedAuthentication.AppId, clientData.AsJson(), deviceRegistration.PublicKey);
            authenticateResponse.CheckUserPresence();

            deviceRegistration.CheckAndUpdateCounter(authenticateResponse.Counter);
        }
    }
}